name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global url."https://github.com/".insteadOf git://github.com/

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
